In [1]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv')
df.dropna(axis=1,inplace=True)
df.head(10)

data stato  codice_regione  denominazione_regione  \
0  2020-02-24T18:00:00   ITA              13                Abruzzo   
1  2020-02-24T18:00:00   ITA              17             Basilicata   
2  2020-02-24T18:00:00   ITA              18               Calabria   
3  2020-02-24T18:00:00   ITA              15               Campania   
4  2020-02-24T18:00:00   ITA               8         Emilia-Romagna   
5  2020-02-24T18:00:00   ITA               6  Friuli Venezia Giulia   
6  2020-02-24T18:00:00   ITA              12                  Lazio   
7  2020-02-24T18:00:00   ITA               7                Liguria   
8  2020-02-24T18:00:00   ITA               3              Lombardia   
9  2020-02-24T18:00:00   ITA              11                 Marche   

         lat       long  ricoverati_con_sintomi  terapia_intensiva  \
0  42.351222  13.398438                       0                  0   
1  40.639471  15.805148                       0                  0   
2  38.905976  16.594402                       0                  0   
3  40.839566  14.250850                       0                  0   
4  44.494367  11.341721                      10                  2   
5  45.649435  13.768136                       0                  0   
6  41.892770  12.483667                       1                  1   
7  44.411493   8.932699                       0                  0   
8  45.466794   9.190347                      76                 19   
9  43.616760  13.518875                       0                  0   

   totale_ospedalizzati  isolamento_domiciliare  totale_positivi  \
0                     0                       0                0   
1                     0                       0                0   
2                     0                       0                0   
3                     0                       0                0   
4                    12                       6               18   
5                     0                       0                0   
6                     2                       0                2   
7                     0                       0                0   
8                    95                      71              166   
9                     0                       0                0   

   variazione_totale_positivi  nuovi_positivi  dimessi_guariti  deceduti  \
0                           0               0                0         0   
1                           0               0                0         0   
2                           0               0                0         0   
3                           0               0                0         0   
4                           0              18                0         0   
5                           0               0                0         0   
6                           0               2                1         0   
7                           0               0                0         0   
8                           0             166                0         6   
9                           0               0                0         0   

   totale_casi  tamponi  
0            0        5  
1            0        0  
2            0        1  
3            0       10  
4           18      148  
5            0       58  
6            3      124  
7            0        1  
8          172     1463  
9            0       16

In [3]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
X = np.array(df['totale_casi']).reshape(-1,1)
scaler = MinMaxScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)
df['min max'] = X_scaled.reshape(1,-1)[0]

In [4]:
scaler.inverse_transform(X_scaled)

array([[      0.],
       [      0.],
       [      0.],
       ...,
       [ 432777.],
       [  50221.],
       [2664353.]])

In [5]:
from sklearn.preprocessing import StandardScaler
X = np.array(df['deceduti']).reshape(-1,1)
scaler = StandardScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)
df['z score'] = X_scaled.reshape(1,-1)[0]

In [6]:
scaler.inverse_transform(X_scaled)

array([[    0.],
       [    0.],
       [    0.],
       ...,
       [ 2372.],
       [  565.],
       [16440.]])

In [7]:
import numpy as np
from sklearn.preprocessing import MaxAbsScaler
X = np.array(df['tamponi']).reshape(-1,1)
scaler = MaxAbsScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)
df['single feature scaling'] = X_scaled.reshape(1,-1)[0]

In [8]:
scaler.inverse_transform(X_scaled)

array([[5.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       ...,
       [4.9722240e+06],
       [5.8376300e+05],
       [3.6333404e+07]])