In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors

# Create the user-item matrix
user_item_matrix = np.array([[5, 3, 0, 1, 4],
                             [0, 2, 3, 5, 1],
                             [1, 0, 5, 2, 4],
                             [4, 0, 2, 0, 0]])

# Create a dataframe for the movies
movies = pd.DataFrame({'title': ['A', 'B', 'C', 'D', 'E']})

# Print the user-item matrix and movies dataframe
print('User-Item Matrix:')
print(user_item_matrix)
print('\nMovies:')
print(movies)


User-Item Matrix:
[[5 3 0 1 4]
 [0 2 3 5 1]
 [1 0 5 2 4]
 [4 0 2 0 0]]

Movies:
  title
0     A
1     B
2     C
3     D
4     E


In [ ]:
# Split the data into training and testing sets
train_size = int(0.8 * len(user_item_matrix))
train_data = user_item_matrix[:train_size]
test_data = user_item_matrix[train_size:]

# Convert the data to numpy arrays
train_data = train_data.astype(float)
test_data = test_data.astype(float)


In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors

# Create the user-item matrix
user_item_matrix = np.array([[5, 3, 0, 1, 4],
                             [0, 2, 3, 5, 1],
                             [1, 0, 5, 2, 4],
                             [4, 0, 2, 0, 0]])

# Create a dataframe for the movies
movies = pd.DataFrame({'title': ['A', 'B', 'C', 'D', 'E']})

# Print the user-item matrix and movies dataframe
print('User-Item Matrix:')
print(user_item_matrix)
print('\nMovies:')
print(movies)

# Compute item-item similarity using cosine similarity
item_sim_matrix = cosine_similarity(user_item_matrix.T)
np.fill_diagonal(item_sim_matrix, 0)

# Use k-nearest neighbors to find the most similar items
knn = NearestNeighbors(metric='cosine', algorithm='brute')
knn.fit(user_item_matrix.T)


def item_based_recommendations(item_id, knn=knn, item_sim_matrix=item_sim_matrix, movies=movies, k=2):
  _, indices = knn.kneighbors(item_sim_matrix[item_id].reshape(1, -1), n_neighbors=k+1)
  similar_items = indices[0][1:]
  recommended_items = [movies.iloc[i]['title'] for i in similar_items]
  return recommended_items

# Make item-based recommendations for item 0
recommendations = item_based_recommendations(0)
print(f'Item-based recommendations for item 0: {recommendations}')

# Use k-nearest neighbors to find the most similar users
knn = NearestNeighbors(metric='cosine', algorithm='brute')
knn.fit(user_item_matrix)

# Make recommendations based on the ratings of similar users
def user_based_recommendations(user_id, knn=knn, user_item_matrix=user_item_matrix, movies=movies, k=2):
    _, indices = knn.kneighbors(user_item_matrix[user_id].reshape(1, -1), n_neighbors=k+1)
    similar_users = indices[0][1:]
    ratings = user_item_matrix[similar_users].mean(axis=0)
    top_items = ratings.argsort()[-k:][::-1]
    recommended_items = [movies.iloc[i]['title'] for i in top_items]
    return recommended_items

# Make user-based recommendations for user 1
recommendations = user_based_recommendations(1)
print(f'User-based recommendations for user 1: {recommendations}')


User-Item Matrix:
[[5 3 0 1 4]
 [0 2 3 5 1]
 [1 0 5 2 4]
 [4 0 2 0 0]]

Movies:
  title
0     A
1     B
2     C
3     D
4     E


ValueError: ignored

In [ ]:
import pandas as pd

# create a small dataset for demo purposes
data = {
    'User': ['User 1', 'User 2', 'User 3', 'User 4', 'User 5'],
    'Movie 1': [4, 3, 4, 2, 5],
    'Movie 2': [3, 4, 2, 5, 3],
    'Movie 3': [5, 2, 3, 4, 4],
    'Movie 4': [2, 5, 4, 3, 2],
    'Movie 5': [1, 4, 5, 2, 3]
}

df = pd.DataFrame(data)
print(df)


     User  Movie 1  Movie 2  Movie 3  Movie 4  Movie 5
0  User 1        4        3        5        2        1
1  User 2        3        4        2        5        4
2  User 3        4        2        3        4        5
3  User 4        2        5        4        3        2
4  User 5        5        3        4        2        3


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

# create a copy of the user-movie matrix without the user column
movie_features = df.drop('User', axis=1)

# calculate the cosine similarity between the movies
movie_similarity = cosine_similarity(movie_features)

# get the top n similar movies to a given movie
def get_similar_movies(movie_index, n=5):
    return movie_similarity[movie_index].argsort()[-n-1:-1][::-1]

# example of getting top 2 similar movies to Movie 1
similar_movies = get_similar_movies(0, n=2)
print('Top 2 similar movies to Movie 1:', similar_movies)


Top 2 similar movies to Movie 1: [4 3]


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

# calculate the cosine similarity between the users
user_similarity = cosine_similarity(df.drop('User', axis=1).T)

# get the top n similar users to a given user
def get_similar_users(user_index, n=5):
    return user_similarity[user_index].argsort()[-n-1:-1][::-1]

# example of getting top 2 similar users to User 1
similar_users = get_similar_users(0, n=2)
print('Top 2 similar users to User 1:', similar_users)


Top 2 similar users to User 1: [2 4]


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import mean_squared_error
from math import sqrt
import pandas as pd

# create a small dataset for demo purposes
data = {
    'User': ['User 1', 'User 2', 'User 3', 'User 4', 'User 5'],
    'Movie 1': [4, 3, 4, 2, 5],
    'Movie 2': [3, 4, 2, 5, 3],
    'Movie 3': [5, 2, 3, 4, 4],
    'Movie 4': [2, 5, 4, 3, 2],
    'Movie 5': [1, 4, 5, 2, 3]
}

df = pd.DataFrame(data)
print(df)

# calculate the mean ratings for each movie
mean_ratings = df.drop('User', axis=1).mean()

# normalize the ratings for each user by subtracting the mean rating
df_norm = df.drop('User', axis=1).apply(lambda x: x - mean_ratings[x.name], axis=1)

# calculate the cosine similarity between the users
user_similarity = cosine_similarity(df_norm.T)

# get the top n similar users to a given user
def get_similar_users(user_index, n=5):
    return user_similarity[user_index].argsort()[-n-1:-1][::-1]

# predict the rating for a movie by a user using collaborative filtering
def predict_rating(user_index, movie_index):
    # get the top 5 similar users to the given user
    similar_users = get_similar_users(user_index, n=5)
    similar_users = get_similar_users(user_index, n=5)
    similar_ratings = df_norm.iloc[similar_users[:-1], movie_index]



    # get the ratings of the similar users for the given movie
    similar_ratings = df_norm.iloc[similar_users.tolist(), movie_index]


    # calculate the predicted rating as the weighted average of the similar ratings
    weight = user_similarity[user_index][similar_users]
    prediction = (similar_ratings * weight).sum() / weight.sum()

    # add back the mean rating to get the final predicted rating
    prediction = prediction + mean_ratings[movie_index]

    return prediction

# example of predicting the rating for Movie 1 by User 1
prediction = predict_rating(0, 0)
print('Predicted rating for Movie 1 by User 1:', prediction)

# calculate the root mean squared error (RMSE) of the predictions
def calculate_rmse(predictions, actual_ratings):
    return sqrt(mean_squared_error(predictions, actual_ratings))

# example of calculating the RMSE of the predictions for all movies by all users
predicted_ratings = df_norm.apply(lambda row: row.index.map(lambda col: predict_rating(row.name, col)), axis=1)
actual_ratings = df_norm.copy()
rmse = calculate_rmse(predicted_ratings.values.flatten(), actual_ratings.values.flatten())
print('RMSE:', rmse)


     User  Movie 1  Movie 2  Movie 3  Movie 4  Movie 5
0  User 1        4        3        5        2        1
1  User 2        3        4        2        5        4
2  User 3        4        2        3        4        5
3  User 4        2        5        4        3        2
4  User 5        5        3        4        2        3
Predicted rating for Movie 1 by User 1: 1.73384953040166


ValueError: ignored

In [ ]:
import numpy as np

# Example matrix
matrix = np.array([
    [1, 2, 3, 0, 0],
    [4, 5, 6, 0, 0],
    [7, 8, 9, 0, 0],
    [0, 0, 0, 10, 11],
    [0, 0, 0, 12, 13]
])


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

# Compute the similarity matrix
content_similarity = cosine_similarity(matrix.T)

# Display the similarity matrix
print("Content similarity matrix:")
print(content_similarity)


Content similarity matrix:
[[1.         0.99559146 0.98692754 0.         0.        ]
 [0.99559146 1.         0.99769319 0.         0.        ]
 [0.98692754 0.99769319 1.         0.         0.        ]
 [0.         0.         0.         1.         0.99997174]
 [0.         0.         0.         0.99997174 1.        ]]


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

# Compute the similarity matrix
user_similarity = cosine_similarity(matrix)

# Display the similarity matrix
print("User similarity matrix:")
print(user_similarity)


User similarity matrix:
[[1.         0.97463185 0.95941195 0.         0.        ]
 [0.97463185 1.         0.99819089 0.         0.        ]
 [0.95941195 0.99819089 1.         0.         0.        ]
 [0.         0.         0.         1.         0.99997109]
 [0.         0.         0.         0.99997109 1.        ]]


In [ ]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import pairwise_distances

# Example matrix
matrix = np.array([
    [1, 2, 3, 0, 0],
    [4, 5, 6, 0, 0],
    [7, 8, 9, 0, 0],
    [0, 0, 0, 10, 11],
    [0, 0, 0, 12, 13]
])

# Compute the user and item similarities
user_similarity = cosine_similarity(matrix)
item_similarity = cosine_similarity(matrix.T)

# Compute the user and item distance matrices
user_distance = pairwise_distances(matrix, metric='cosine')
item_distance = pairwise_distances(matrix.T, metric='cosine')

# Make predictions based on the user-item matrix
user_predictions = user_similarity.dot(matrix) / np.array([np.abs(user_similarity).sum(axis=1)]).T
item_predictions = matrix.dot(item_similarity)

# Display the predictions
print("User-based predictions:")
print(user_predictions)
print("Item-based predictions:")
print(item_predictions)


User-based predictions:
[[ 3.95849954  4.95849954  5.95849954  0.          0.        ]
 [ 4.02377442  5.02377442  6.02377442  0.          0.        ]
 [ 4.04116988  5.04116988  6.04116988  0.          0.        ]
 [ 0.          0.          0.         10.99998554 11.99998554]
 [ 0.          0.          0.         11.00001446 12.00001446]]
Item-based predictions:
[[ 5.95196554  5.98867103  5.98231393  0.          0.        ]
 [14.89952253 14.96852497 14.93617613  0.          0.        ]
 [23.84707953 23.94837891 23.89003833  0.          0.        ]
 [ 0.          0.          0.         20.99968909 20.99971735]
 [ 0.          0.          0.         24.99963256 24.99966082]]
